############################################################
# +------------------------------------------------------+ #
# |                          SHOP                        | #
# +------------------------------------------------------+ #
############################################################

# Les entités qui peuvent être vendus aux autres joueurs
entity-sell-shop:
  - PIG
  - CHICKEN

# Le nom correspondant à chaque entité
entity-name-shop:
  pig: "Cochon"
  chicken: "Poulet"

# La tête correspondant à chaque entité
# Note: Tu peux mettre plusieurs tête par mob, dans la boutique ca prendra aléatoirement.
#       En revanche pour tout le reste, ca prendra la première tête mise dans la liste !
entity-head-shop:
  pig:
    - hdb-14201
    - hdb-38574
  chicken:
    - hdb-659
    - hdb-35652

# Le prix de chaque entité
entity-price-shop:
  pig: 5
  chicken: 10

# La variation du prix (en %)
price-variation-shop: 10

############################################################
# +------------------------------------------------------+ #
# |                       BOUCHERIE                      | #
# +------------------------------------------------------+ #
############################################################

# Les entités qui peuvent être vendus à la boucherie
entity-sell-butcher:
  - PIG
  - CHICKEN

# Le nom correspondant à chaque entité
entity-name-butcher:
  pig: "Cochon"
  chicken: "Poulet"

# La tête correspondant à chaque entité
entity-head-butcher:
  pig: hdb-26071
  chicken: hdb-33798

# Le prix de chaque entité
entity-price-butcher:
  pig: 2.5
  chicken: 5

# La variation du prix (en %)
price-variation-butcher: 10